### ISSUE TITLE
Es gibt noch einige Warnings

### ISSUE THREAD

**Issue by olien** [medienfeuer/be_branding#12]
`Warning: Use of undefined constant hex2rgb - assumed 'hex2rgb' (this will throw an Error in a future version of PHP) in /Users/abc/Sites/def/redaxo/src/addons/be_branding/boot.php on line 25
Warning: Use of undefined constant rgb2hex - assumed 'rgb2hex' (this will throw an Error in a future version of PHP) in /Users/abc/Sites/def/redaxo/src/addons/be_branding/boot.php on line 44
Warning: Use of undefined constant rgba2hex - assumed 'rgba2hex' (this will throw an Error in a future version of PHP) in /Users/abc/Sites/def/redaxo/src/addons/be_branding/boot.php on line 58
Warning: Use of undefined constant makeFavIcon - assumed 'makeFavIcon' (this will throw an Error in a future version of PHP) in /Users/abc/Sites/def/redaxo/src/addons/be_branding/boot.php on line 72`

**Comment by medienfeuer** [comment]
Danke. Kümmere ich mich drum.
